name: Build and Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.prod
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env.prod
          echo "AI_TOKEN=${{ secrets.AI_TOKEN }}" >> .env.prod
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env.prod

      - name: Build Docker image
        id: docker_build
        run: |
          docker build -t gachibot:latest -t gachibot:${{ github.sha }} .

      - name: Deploy container
        id: deploy
        run: |
          CURRENT_IMAGE=$(docker ps -q --filter "name=gachibot_container" | xargs -r docker inspect --format '{{.Config.Image}}' || echo "none")
          echo "Current image: $CURRENT_IMAGE"

          docker stop gachibot_container || true
          docker rm gachibot_container || true
          
          docker run -d --name gachibot_container \
            --restart unless-stopped \
            -v $PWD/.env.prod:/app/.env.prod \
            gachibot:latest

          echo "Deployment successful"
